### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by VKonstantakos** [pierclgr/CRISPRLearner#1]
I'm getting this warning and NaN Spearman Correlations (or negative ones) while running main.py (option 1 "Train models using all training sets")  :
![image](https://user-images.githubusercontent.com/60272607/73498987-86f55780-43c7-11ea-86c1-32ff18397efa.png)
![image](https://user-images.githubusercontent.com/60272607/73499008-94aadd00-43c7-11ea-8d6d-149c5185ffcd.png)
![image](https://user-images.githubusercontent.com/60272607/73499023-9d031800-43c7-11ea-8913-32291239168d.png)

I am not sure what's causing it. Any help would be appreciated.

**Comment by pierclgr** [comment]
Unfortunately it is an error I still have not fixed. I honestly don't know what it's causing it.
